### ISSUE TITLE
complete Metafield resource 

### ISSUE THREAD

**Issue by Alua-Kinzhebayeva** [microapps/Nodify-Shopify#18]
[Metafield](https://docs.shopify.com/api/metafield) resource requires to be completed and have associated integration tests. 
P.S. if you look into source code, you will find that a resource inherits from base or base_child. Metafield has endpoints that "belong" to both base classes.
P.P.S. actual implementation is not sufficient, and has to be overwritten to support both cases.

**Comment by lpinca** [comment]
A possible solution is to not inherit and create a `Metafield` class with all the required methods. For example the `all` method can have the following signature:

```js
session.metafields.all(owner, params, callback);
```

where `owner` is an optional object that specify the owner resource e.g.:

```js
{ id: 632910392, resource: 'product' }
```

when we want to get the metafileds of a store we can omit the `owner` argument and build the URL accordingly. A similar approach can be used for the other methods.

The only thing that is a bit confusing is when the owner resource is `product_image`. In this case the documentation uses the following endpoint:
```
GET /admin/metafields.json?metafield[owner_id]=850703190&metafield[owner_resource]=product_image
```
which is different from all the others and I guess this is because [`Product Image`](https://docs.shopify.com/api/product_image) has its own parent.
I wonder what is the endpoint to create, update and delete a metafield that belongs to a product image. The documentation does not specify this.

Thoughts?

**Comment by Alua-Kinzhebayeva** [comment]
Good solution.
At the moment I am not aware of those endpoints.
