### ISSUE TITLE
Move package to pure JS

### ISSUE THREAD

**Issue by lpinca** [microapps/Nodify-Shopify#59]
Many Node.js developers (including myself) have this reaction

![zhl9r15](https://cloud.githubusercontent.com/assets/1443911/11269838/11bad772-8eba-11e5-9370-0002b8184198.gif)

when [they have to read a module written in CoffeeScript](http://nodejsreactions.tumblr.com/post/99062009952/when-i-have-to-read-a-module-written-in).

On top of this, the test suite is already written in JavaScript. I think that it makes sense to port everything to JavaScript and maybe use ES2015 with [Babel](https://babeljs.io/).

**Comment by Alua-Kinzhebayeva** [comment]
I agree with CoffeeScript part. I personally don't like it. 
I have not been here since the beginning of the module, but I can imagine why people used it. I think they were (and still are) hardworking Rubyists/Full Stacks (and possibly tried to make context switch cheaper) who wanted to have js modules beautiful and consistent. 
As for porting completely to JS, I would first finish extend module's functionality, like adding new resources to session object so clients have access to them in their code. Also enabling use of new resources to those who are developing public apps. I know those things are not mutually exclusive and don't have to be sequential, it is my personal choice - functionality first. Mixed style of quotes might not look well, but at the moment I am more concerned with helping people to use the module.

**Comment by lpinca** [comment]
I agree with you @Alua-Kinzhebayeva, done is better than perfect, but I also think that clean clode is a feature. A lot of code in this repo is untouchable because it's such a mess.

**Comment by Alua-Kinzhebayeva** [comment]
I guess you have an upcoming pr with port to JS. if it is the case, it will be happily merged

**Comment by lpinca** [comment]
No, not yet, but maybe in the next few days :wink:

**Comment by carlosvillu** [comment]
The truth is I chose CoffeeScript because, at the time, it was the platform that had more potential to develop the client. None if those reasons hold today, so it makes sense to port to ES6, though I would not only migrate the code but would also review the design,

- getting rid of the asynchronous API using callbacks
- using a reactive development style, returning streams in every call
- favoring composition over inheritance

Sorry I don't have enough time to contribute to the project, but I'm amazed at what it's becoming of it.

**Comment by kenrick** [comment]
:+1:

**Comment by lpinca** [comment]
I close this as a significant refactor where CoffeeScript is no longer used, has been completed.
We still don't take full advantage of ES2015 syntax (import, export, destructuring assignment, etc.), but it a big step forward.
